### ISSUE TITLE
How to output vertical velocity?

### ISSUE THREAD

**Issue by weatherforecasterwhai** [google-research/neuralgcm#68]
Would you please help me to output vertical velocity ? Vertical velocity is so important.
Running the following after "Advancing in time" in "Deep-dive intor trained models" in the document:
"
from dinosaur import primitive_equations
omega=primitive_equations.compute_vertical_velocity(advanced,model.data_coords)
"
But it runs in following errors:

Traceback (most recent call last):
File "", line 1, in
File "/home/whai/anaconda3/lib/python3.11/site-packages/dinosaur/primitive_equations.py", line 234, in compute_vertical_velocity
sigma_dot_boundaries = compute_diagnostic_state(state, coords).sigma_dot_full
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/whai/anaconda3/lib/python3.11/contextlib.py", line 81, in inner
return func(*args, **kwds)
^^^^^^^^^^^^^^^^^^^
File "/home/whai/anaconda3/lib/python3.11/site-packages/dinosaur/primitive_equations.py", line 175, in compute_diagnostic_state
nodal_vorticity = to_nodal_fn(state.vorticity)
^^^^^^^^^^^^^^^
AttributeError: 'ModelState' object has no attribute 'vorticity'

The "advaned" state "pprint" has vorticity. Would you please help me to fix this ?

**Comment by shoyer** [comment]
There is a nested State object -- try passing `advanced.state` into `compute_diagnostic_state()`.

**Comment by weatherforecasterwhai** [comment]
Thank you again, but sorry to ask for your help again:
the output vertical velocity from compute_vertical_velocity is on sigma levels,
so I try to use **model.model_coords.horizontal.to_nodal(vertical velocity)** as you said in #8.
However it works with this error:
**size of label  '1' for operand  1 (65)  does not match previous terms (64).**
I've searched and can't fix it by myself. The full traceback is like this:
![1715262518652](https://github.com/google-research/neuralgcm/assets/162259387/5ddb7d4c-560b-4b05-947d-e594b941623a)
